# Generated by Django 5.2.6 on 2025-12-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_employee_delete_customuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="can_manage_content",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="can_manage_products",
        ),
    ]
