# Generated by Django 5.2.6 on 2025-11-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productsApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=7,
                null=True,
                verbose_name="产品价格",
            ),
        ),
    ]
