# Generated by Django 5.2.6 on 2025-11-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0002_resume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ("-publishDate",),
                "verbose_name": "招聘广告",
                "verbose_name_plural": "招聘广告",
            },
        ),
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2025-11-20", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
