# Generated by Django 5.2.6 on 2025-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0003_alter_ad_options_alter_resume_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2025-11-21", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
