# Generated by Django 5.2.6 on 2025-12-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0005_alter_resume_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2025-12-20", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
