# Generated by Django 5.2.6 on 2025-12-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0006_alter_resume_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
