# Generated by Django 5.2.6 on 2026-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0007_alter_resume_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuickFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("message", models.TextField(verbose_name="需求说明")),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
            ],
            options={
                "verbose_name": "快捷留言",
                "verbose_name_plural": "快捷留言",
            },
        ),
    ]
