# Generated by Django 5.2.6 on 2026-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0008_quickfeedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickfeedback",
            name="reply",
            field=models.TextField(blank=True, null=True, verbose_name="官方回复内容"),
        ),
        migrations.AddField(
            model_name="quickfeedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                ],
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
    ]
