# Generated by Django 5.2.6 on 2026-01-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contactApp", "0009_quickfeedback_reply_quickfeedback_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="position",
        ),
        migrations.AddField(
            model_name="resume",
            name="ad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumes",
                to="contactApp.ad",
                verbose_name="应聘岗位",
            ),
            preserve_default=False,
        ),
    ]
