"""
Django settings for HengDaProject project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-qpn=%6j9#3=g!c0(8len_2wa*6dfwvr_49#fs1^@qv!e%nnsya"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# 设置开放权限
ALLOWED_HOSTS = [
    '47.109.98.170',
    '127.0.0.1',
    "localhost",
    # '*',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'homeApp', #首页
    'aboutApp',# 简介
    'contactApp',
    'newsApp',
    'productsApp',
    'serviceApp',
    'scienceApp',
    'DjangoUeditor',# 添加富文本编辑器
    'haystack',# 添加搜索应用
    "widget_tweaks",# 添加模型表单组件定制化渲染应用
    'accounts', # 用户
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = "HengDaProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HengDaProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',    # 修改数据库引擎
        'NAME': 'hengda_db',                    # 数据库名称
        'USER': 'hengda_user',                           # MySQL 用户名
        'PASSWORD': '78245af50c508559',              # MySQL 密码
        'HOST': '127.0.0.1',                      # 数据库主机地址
        'PORT': '3306',                           # MySQL 默认端口
        'OPTIONS': {
            'charset': 'utf8mb4',                 # 设置字符集
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",  # 严格模式
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = '/www/wwwroot/HengDaProject2/staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'newsApp.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}
HAYSTACK_SEARCH_RESULTS_PER_PAGE = 10
HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'

EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25 #端口号
EMAIL_HOST_USER = '1718352874@qq.com' #企业QQ号
EMAIL_HOST_PASSWORD = 'bwulwgfedtdxdihh' # 授权码
EMAIL_USE_TLS = True


CACHES = {
    'default':{
        'BACKEND':'django.core.cache.backends.db.DatabaseCache',
        'LOCATION':'cache_table_home',
        'TIMEOUT': 600,
        'OPTIONS':{
            'MAX_ENTRIES': 2000
        }
    }
}
# 设置自定义用户模型
AUTH_USER_MODEL = 'accounts.Employee'

CSRF_TRUSTED_ORIGINS = [
    "http://47.109.98.170",
    "http://127.0.0.1",
    "http://localhost",
]

CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
