# Generated by Django 5.2.6 on 2025-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mynew",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="news/", verbose_name="展报"
            ),
        ),
    ]
